export const UseSchema: string = 'USE SCHEMA {schemaName};'
export const ShowSchemas: string = 'SHOW SCHEMAS'
export const CreateSchema: string = 'CREATE OR REPLACE SCHEMA {schemaName};'
export const DropSchema: string = 'DROP SCHEMA {schemaName};'
export const ShowStages: string = 'SHOW STAGES'